import {
  User,
  Session,
  LearningRoom,
  Review,
  Recording,
  TimeSlot,
  CreditTransaction,
  Connection,
  Message,
  Conversation,
  SkillExchangeOffer,
  LearningPath,
  NotificationItem,
  SkillDefinition,
} from "@/types";

export const SKILL_CATALOG: SkillDefinition[] = [
  // Technology
  { id: "tech-python", name: "Python", category: "technology", subSkills: ["Django", "FastAPI", "Pandas", "NumPy", "PyTorch", "Automation"], description: "Versatile programming for web, scripting, and data science", isPopular: true, icon: "code" },
  { id: "tech-javascript", name: "JavaScript", category: "technology", subSkills: ["ES6+", "Async/Await", "DOM", "Node.js", "TypeScript"], description: "The core language of the modern web", isPopular: true, icon: "code" },
  { id: "tech-typescript", name: "TypeScript", category: "technology", subSkills: ["Type Systems", "Generics", "Strict Mode", "React TS"], description: "Typed JavaScript at any scale", isPopular: true, icon: "code" },
  { id: "tech-react", name: "React", category: "technology", subSkills: ["Hooks", "State Management", "Component Design", "Server Components"], description: "Leading UI library for modern web apps", isPopular: true, icon: "code" },
  { id: "tech-nextjs", name: "Next.js", category: "technology", subSkills: ["App Router", "SSR", "API Routes", "Turbopack", "SEO"], description: "Production React framework", isPopular: true, icon: "code" },
  { id: "tech-nodejs", name: "Node.js", category: "technology", subSkills: ["Express", "REST APIs", "Microservices", "WebSockets"], description: "Server-side JavaScript runtime", isPopular: true, icon: "code" },
  { id: "tech-java", name: "Java", category: "technology", subSkills: ["Spring Boot", "OOP", "Concurrency", "JVM Performance"], description: "Enterprise grade programming language", isPopular: false, icon: "code" },
  { id: "tech-csharp", name: "C#", category: "technology", subSkills: [".NET Core", "Unity Game Dev", "LINQ", "ASP.NET"], description: "Modern language for cloud, desktop, and game development", isPopular: false, icon: "code" },
  { id: "tech-cpp", name: "C++", category: "technology", subSkills: ["Pointers", "Memory Management", "STL", "Game Engines", "Algorithms"], description: "High-performance systems programming", isPopular: false, icon: "code" },
  { id: "tech-rust", name: "Rust", category: "technology", subSkills: ["Ownership", "Async Rust", "WebAssembly", "Clippy", "Cargo"], description: "Safe, concurrent systems language", isPopular: true, icon: "code" },
  { id: "tech-go", name: "Go", category: "technology", subSkills: ["Goroutines", "Channels", "gRPC", "Microservices"], description: "Clean, fast language built for cloud services", isPopular: false, icon: "code" },
  { id: "tech-flutter", name: "Flutter", category: "technology", subSkills: ["Dart", "Cross-Platform UI", "State Management", "Animations"], description: "Build natively compiled multi-platform apps", isPopular: true, icon: "smartphone" },
  { id: "tech-ai-ml", name: "Machine Learning & AI", category: "technology", subSkills: ["Neural Networks", "LLMs", "Scikit-Learn", "Computer Vision", "NLP"], description: "Build intelligent systems and model architectures", isPopular: true, icon: "cpu" },
  { id: "tech-data-analytics", name: "Data Analytics & SQL", category: "technology", subSkills: ["PostgreSQL", "BigQuery", "Tableau", "PowerBI", "Data Modeling"], description: "Querying, data pipelines and business intelligence", isPopular: true, icon: "database" },
  { id: "tech-cybersecurity", name: "Cybersecurity", category: "technology", subSkills: ["Ethical Hacking", "Network Security", "Cryptography", "Pen Testing"], description: "Securing applications and digital infrastructure", isPopular: false, icon: "shield" },
  { id: "tech-devops", name: "DevOps & Cloud", category: "technology", subSkills: ["Docker", "Kubernetes", "AWS", "CI/CD", "Terraform"], description: "Automating deployments and cloud operations", isPopular: true, icon: "cloud" },
  { id: "tech-blockchain", name: "Blockchain", category: "technology", subSkills: ["Solidity", "Smart Contracts", "Web3.js", "Ethereum"], description: "Decentralized applications and ledger tech", isPopular: false, icon: "link" },

  // Creative
  { id: "creat-video-editing", name: "Video Editing", category: "creative", subSkills: ["Premiere Pro", "DaVinci Resolve", "Color Grading", "Sound Design", "Pacing"], description: "Craft compelling stories and high-impact edits", isPopular: true, icon: "video" },
  { id: "creat-photoshop", name: "Photoshop & Photo Editing", category: "creative", subSkills: ["Retouching", "Compositing", "Lightroom", "Color Correction"], description: "Image manipulation and visual creation", isPopular: true, icon: "image" },
  { id: "creat-figma", name: "UI/UX Design with Figma", category: "creative", subSkills: ["Design Systems", "Prototyping", "User Research", "Wireframing"], description: "Design user-centered digital products", isPopular: true, icon: "layout" },
  { id: "creat-motion-graphics", name: "Motion Graphics & 3D", category: "creative", subSkills: ["After Effects", "Blender", "3D Modeling", "Keyframing"], description: "Dynamic animations and 3D visual assets", isPopular: true, icon: "activity" },
  { id: "creat-photography", name: "Photography", category: "creative", subSkills: ["Composition", "Lighting", "Portrait", "Street", "Manual Camera Mode"], description: "Capturing light and powerful visual stories", isPopular: false, icon: "camera" },
  { id: "creat-music-prod", name: "Music Production", category: "creative", subSkills: ["Ableton Live", "FL Studio", "Beat Making", "Mixing", "Mastering"], description: "Composing and producing studio-grade tracks", isPopular: true, icon: "music" },
  { id: "creat-guitar", name: "Guitar", category: "creative", subSkills: ["Acoustic", "Electric", "Chords", "Fingerstyle", "Improvisation"], description: "From beginner chords to stage solos", isPopular: false, icon: "music" },
  { id: "creat-piano", name: "Piano & Keys", category: "creative", subSkills: ["Classical", "Jazz Chords", "Sight Reading", "Ear Training"], description: "Mastering keys, rhythm, and harmonic theory", isPopular: false, icon: "music" },
  { id: "creat-content-creation", name: "Content Creation", category: "creative", subSkills: ["YouTube Strategy", "Thumbnails", "Storytelling", "Short-Form Video"], description: "Building audiences and viral creative content", isPopular: true, icon: "share-2" },

  // Business
  { id: "biz-entrepreneurship", name: "Entrepreneurship & Startups", category: "business", subSkills: ["Idea Validation", "Pitching", "GTM Strategy", "Unit Economics"], description: "Building and scaling successful ventures", isPopular: true, icon: "trending-up" },
  { id: "biz-marketing", name: "Digital Marketing & SEO", category: "business", subSkills: ["Growth Hacking", "Google Ads", "Content Marketing", "Email Funnels"], description: "Acquiring customers and boosting visibility", isPopular: true, icon: "target" },
  { id: "biz-public-speaking", name: "Public Speaking & Pitching", category: "business", subSkills: ["Stage Presence", "Storytelling", "Overcoming Anxiety", "Slide Design"], description: "Captivate audiences and deliver memorable talks", isPopular: true, icon: "mic" },
  { id: "biz-finance", name: "Personal Finance & Investing", category: "business", subSkills: ["Stock Market", "Financial Modeling", "Budgeting", "Real Estate"], description: "Building wealth and managing financial health", isPopular: true, icon: "dollar-sign" },
  { id: "biz-product-management", name: "Product Management", category: "business", subSkills: ["Roadmapping", "User Stories", "Agile/Scrum", "Metrics & KPIs"], description: "Guiding product lifecycle from idea to launch", isPopular: false, icon: "layers" },

  // Languages
  { id: "lang-english", name: "English Fluency", category: "languages", subSkills: ["Conversational", "Business English", "Pronunciation", "IELTS/TOEFL Prep"], description: "Speak clearly and confidently in international settings", isPopular: true, icon: "globe" },
  { id: "lang-spanish", name: "Spanish", category: "languages", subSkills: ["Grammar", "Conversational", "Vocabulary", "DELE Prep"], description: "Master the world's second most spoken native language", isPopular: true, icon: "globe" },
  { id: "lang-japanese", name: "Japanese", category: "languages", subSkills: ["Hiragana & Katakana", "Kanji", "JLPT Prep", "Anime & Culture"], description: "Learn spoken Japanese and writing systems", isPopular: true, icon: "globe" },
  { id: "lang-german", name: "German", category: "languages", subSkills: ["Grammar", "Conversational", "Goethe Zertifikat", "Work Culture"], description: "Language for European tech and academia", isPopular: false, icon: "globe" },
  { id: "lang-hindi", name: "Hindi & Urdu", category: "languages", subSkills: ["Spoken Hindi", "Vocabulary", "Script Reading", "Cultural Idioms"], description: "Connect with over 600 million speakers worldwide", isPopular: true, icon: "globe" },
  { id: "lang-telugu", name: "Telugu", category: "languages", subSkills: ["Conversational", "Grammar", "Literary Telugu", "Daily Idioms"], description: "Rich South Indian language with vibrant cinema and culture", isPopular: false, icon: "globe" },
  { id: "lang-arabic", name: "Arabic", category: "languages", subSkills: ["Modern Standard Arabic", "Dialects", "Script", "Grammar"], description: "Classic and contemporary Middle Eastern language", isPopular: false, icon: "globe" },

  // Academics
  { id: "acad-math", name: "Mathematics & Statistics", category: "academics", subSkills: ["Calculus", "Linear Algebra", "Probability", "Discrete Math"], description: "Foundational math for engineering, physics, and AI", isPopular: true, icon: "calculator" },
  { id: "acad-physics", name: "Physics", category: "academics", subSkills: ["Mechanics", "Electromagnetism", "Thermodynamics", "Quantum"], description: "Understanding the fundamental laws of nature", isPopular: false, icon: "zap" },
  { id: "acad-cs", name: "Computer Science Theory", category: "academics", subSkills: ["Algorithms & DSA", "Operating Systems", "Computer Architecture", "Automata"], description: "Core academic principles of computing", isPopular: true, icon: "terminal" },

  // Sports & Fitness (Sports Mode)
  { id: "sport-cricket", name: "Cricket", category: "sports", subSkills: ["Batting Technique", "Fast Bowling", "Spin Bowling", "Fielding & Agility", "Wicketkeeping", "Cricket Strategy", "Match Fitness"], description: "Batting mastery, bowling variations, and tactical fielding", isPopular: true, icon: "award" },
  { id: "sport-football", name: "Football (Soccer)", category: "sports", subSkills: ["Dribbling", "Passing & Vision", "Shooting Technique", "Defending", "Goalkeeping", "Tactical Positioning"], description: "Ball control, positioning, and match strategy", isPopular: true, icon: "award" },
  { id: "sport-badminton", name: "Badminton", category: "sports", subSkills: ["Footwork & Agility", "Smash Technique", "Net Play & Drop Shots", "Doubles Coordination", "Defensive Clears"], description: "Speed, deceptive wrist work, and court coverage", isPopular: true, icon: "award" },
  { id: "sport-chess", name: "Chess", category: "sports", subSkills: ["Opening Repertoire", "Tactical Combinations", "Middlegame Strategy", "Endgame Technique", "Blitz & Rapid Timing"], description: "Deep tactical calculation and positional mastery", isPopular: true, icon: "crosshair" },
  { id: "sport-yoga", name: "Yoga & Mindfulness", category: "sports", subSkills: ["Vinyasa Flow", "Hatha Postures", "Breathwork (Pranayama)", "Flexibility", "Meditation"], description: "Harmonizing mind, breath, and body strength", isPopular: true, icon: "heart" },
  { id: "sport-fitness", name: "Gym & Calisthenics", category: "sports", subSkills: ["Bodyweight Training", "Hypertrophy", "Form & Mechanics", "Mobility", "Diet & Nutrition"], description: "Strength building, body mechanics, and endurance", isPopular: true, icon: "activity" },
  { id: "sport-tennis", name: "Tennis", category: "sports", subSkills: ["Forehand Topspin", "One/Two-Handed Backhand", "Serve Mechanics", "Volley", "Court Movement"], description: "Racket precision, court movement, and match stamina", isPopular: false, icon: "award" },

  // Life Skills & Hobbies
  { id: "life-cooking", name: "Cooking & Baking", category: "life_skills", subSkills: ["Knife Skills", "Italian Cuisine", "Sourdough Baking", "Meal Prep", "Flavors & Seasoning"], description: "Culinary arts and kitchen confidence", isPopular: true, icon: "coffee" },
  { id: "life-time-mgmt", name: "Time Management & Productivity", category: "life_skills", subSkills: ["Deep Work", "Atomic Habits", "Second Brain", "Focus Frameworks"], description: "Structuring high-output days without burnout", isPopular: false, icon: "clock" },
  { id: "hobby-gaming", name: "Gaming & Esports", category: "hobbies", subSkills: ["Strategy", "Aim Training", "Team Communication", "Game Analysis"], description: "Tactical gaming, team coordination, and mechanics", isPopular: false, icon: "gamepad" },
  { id: "hobby-podcasting", name: "Podcasting & Audio", category: "hobbies", subSkills: ["Interviewing", "Microphone Technique", "Audio Editing", "Publishing"], description: "Launching and hosting engaging audio shows", isPopular: false, icon: "mic" },
];

export const SEMANTIC_SEARCH_MAP: { query: string; suggestedSkills: string[]; reason: string }[] = [
  { query: "make websites", suggestedSkills: ["Web Development", "HTML", "CSS", "JavaScript", "React", "UI/UX Design with Figma"], reason: "Includes front-end, visual design, and interactive coding required to build modern websites" },
  { query: "youtube videos", suggestedSkills: ["Video Editing", "Content Creation", "Photoshop & Photo Editing", "Photography", "Motion Graphics & 3D"], reason: "Covers editing workflows, thumbnail design, and visual storytelling for YouTube" },
  { query: "cricket", suggestedSkills: ["Cricket", "Batting Technique", "Fast Bowling", "Fielding & Agility", "Cricket Strategy", "Gym & Calisthenics"], reason: "Covers technical batting/bowling execution, field positioning, and sports fitness" },
  { query: "learn ai", suggestedSkills: ["Python", "Machine Learning & AI", "Mathematics & Statistics", "Data Analytics & SQL"], reason: "Provides the programming, mathematical, and algorithmic foundation for AI" },
  { query: "mobile apps", suggestedSkills: ["Flutter", "React", "JavaScript", "TypeScript", "UI/UX Design with Figma"], reason: "Technologies for building iOS and Android cross-platform applications" },
  { query: "speak english", suggestedSkills: ["English Fluency", "Public Speaking & Pitching", "Conversational"], reason: "Conversational practice, pronunciation drills, and confidence building" },
  { query: "chess", suggestedSkills: ["Chess", "Tactical Combinations", "Opening Repertoire", "Endgame Technique"], reason: "Comprehensive chess training from openings to calculation" },
];

export const DEMO_USERS: User[] = [
  {
    id: "u1",
    name: "Sarah Chen",
    email: "sarah@synapselearn.io",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    bio: "Senior Full-Stack Architect & AI enthusiast. Passionate about teaching modern web tech and looking to master video editing for tech tutorials.",
    location: "San Francisco, CA",
    preferredLanguages: ["English", "Mandarin"],
    weeklyHours: 6,
    availableDays: [1, 3, 5, 6], // Mon, Wed, Fri, Sat
    availableTimes: ["evening", "afternoon"],
    preferredMethods: ["video", "screen_share", "project_based"],
    learningGoals: ["Master DaVinci Resolve & Premiere", "Learn conversational Spanish for travel"],
    interests: ["Artificial Intelligence", "Indie Hacking", "Documentary Filmmaking", "Cycling"],
    skillsTeach: [
      { name: "React", category: "technology", subSkill: "Next.js & Hooks", level: "Expert", yearsOfExp: 7 },
      { name: "TypeScript", category: "technology", subSkill: "Type Systems", level: "Advanced", yearsOfExp: 5 },
      { name: "Python", category: "technology", subSkill: "FastAPI & Pandas", level: "Intermediate", yearsOfExp: 3 },
    ],
    skillsLearn: [
      { name: "Video Editing", category: "creative", subSkill: "Color Grading & Pacing", level: "Intermediate" },
      { name: "Spanish", category: "languages", subSkill: "Conversational", level: "Beginner" },
    ],
    credits: 24,
    linkedinUrl: "https://linkedin.com/in/sarahchen",
    githubUrl: "https://github.com/sarahchen",
    isLinkedInVerified: true,
    isGitHubVerified: true,
    rating: 4.95,
    totalReviews: 48,
    totalSessionsTaught: 64,
    totalSessionsLearned: 16,
    completedExchanges: 12,
    streakDays: 18,
    badges: ["Helpful Teacher", "Top Mentor", "Consistent Learner"],
    projects: [
      { title: "React Superhooks", link: "https://github.com/sarahchen/hooks", description: "Open-source state library with 4k GitHub stars" },
    ],
    role: "user",
    createdAt: "2024-01-15",
  },
  {
    id: "u2",
    name: "Marcus Johnson",
    email: "marcus@synapselearn.io",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    bio: "Lead Product Designer and Video Creator. Can teach end-to-end Figma design systems, motion graphics, and video editing in exchange for Python & Web Dev.",
    location: "Austin, TX",
    preferredLanguages: ["English"],
    weeklyHours: 8,
    availableDays: [1, 2, 4, 6],
    availableTimes: ["morning", "afternoon", "evening"],
    preferredMethods: ["video", "screen_share", "chat"],
    learningGoals: ["Build full-stack SaaS apps using React and Python", "Understand backend APIs"],
    interests: ["Design Systems", "Sci-Fi Filmmaking", "Generative Art", "Coffee Brewing"],
    skillsTeach: [
      { name: "Video Editing", category: "creative", subSkill: "Premiere Pro & DaVinci", level: "Expert", yearsOfExp: 6 },
      { name: "UI/UX Design with Figma", category: "creative", subSkill: "Design Systems", level: "Expert", yearsOfExp: 8 },
      { name: "Photoshop & Photo Editing", category: "creative", subSkill: "Compositing", level: "Advanced", yearsOfExp: 5 },
    ],
    skillsLearn: [
      { name: "Python", category: "technology", subSkill: "Web Scraping & APIs", level: "Beginner" },
      { name: "React", category: "technology", subSkill: "Component Design", level: "Intermediate" },
    ],
    credits: 19,
    linkedinUrl: "https://linkedin.com/in/marcusj",
    githubUrl: undefined,
    isLinkedInVerified: true,
    isGitHubVerified: false,
    rating: 4.88,
    totalReviews: 35,
    totalSessionsTaught: 42,
    totalSessionsLearned: 24,
    completedExchanges: 9,
    streakDays: 12,
    badges: ["Helpful Teacher", "Fast Learner"],
    role: "user",
    createdAt: "2024-02-20",
  },
  {
    id: "u3",
    name: "Arjun Sharma",
    email: "arjun@synapselearn.io",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80",
    bio: "Cricket Academy Coach & Fitness Specialist. Ex-state cricketer. I teach batting biomechanics, tactical fielding, and athletic fitness. Want to learn Python for cricket analytics.",
    location: "Bengaluru, India",
    preferredLanguages: ["English", "Hindi", "Telugu"],
    weeklyHours: 10,
    availableDays: [0, 2, 4, 5, 6], // Sun, Tue, Thu, Fri, Sat
    availableTimes: ["morning", "evening"],
    preferredMethods: ["video", "in_person", "group", "project_based"],
    learningGoals: ["Build automated cricket performance dashboards in Python", "Learn Data Analytics"],
    interests: ["Cricket Biomechanics", "Sports Science", "Data Analytics", "Chess"],
    skillsTeach: [
      { name: "Cricket", category: "sports", subSkill: "Batting Technique", level: "Expert", yearsOfExp: 12 },
      { name: "Gym & Calisthenics", category: "sports", subSkill: "Mobility & Endurance", level: "Advanced", yearsOfExp: 7 },
      { name: "Cricket", category: "sports", subSkill: "Cricket Strategy", level: "Expert", yearsOfExp: 10 },
    ],
    skillsLearn: [
      { name: "Python", category: "technology", subSkill: "Data Analytics & SQL", level: "Beginner" },
      { name: "Data Analytics & SQL", category: "technology", subSkill: "Tableau & Dashboards", level: "Beginner" },
    ],
    credits: 32,
    linkedinUrl: "https://linkedin.com/in/arjun-cricket",
    githubUrl: "https://github.com/arjunsharma",
    isLinkedInVerified: true,
    isGitHubVerified: true,
    rating: 4.96,
    totalReviews: 54,
    totalSessionsTaught: 76,
    totalSessionsLearned: 11,
    completedExchanges: 14,
    streakDays: 25,
    badges: ["Helpful Teacher", "Top Mentor", "Community Builder"],
    role: "user",
    createdAt: "2023-11-05",
  },
  {
    id: "u4",
    name: "Elena Rodriguez",
    email: "elena@synapselearn.io",
    avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
    bio: "Certified Yoga & Mindfulness Instructor from Madrid. Native Spanish speaker. I love cross-cultural skill exchanges and want to learn Italian cooking and digital marketing.",
    location: "Madrid, Spain",
    preferredLanguages: ["Spanish", "English", "French"],
    weeklyHours: 5,
    availableDays: [1, 2, 3, 5],
    availableTimes: ["morning", "afternoon"],
    preferredMethods: ["video", "voice", "group"],
    learningGoals: ["Launch an online yoga academy", "Master traditional sourdough and Italian pasta"],
    interests: ["Pranayama", "Mediterranean Cooking", "Podcasting", "Travel"],
    skillsTeach: [
      { name: "Spanish", category: "languages", subSkill: "Conversational & Grammar", level: "Expert", yearsOfExp: 10 },
      { name: "Yoga & Mindfulness", category: "sports", subSkill: "Vinyasa Flow & Breathwork", level: "Expert", yearsOfExp: 8 },
      { name: "Public Speaking & Pitching", category: "business", subSkill: "Voice Modulation", level: "Advanced", yearsOfExp: 4 },
    ],
    skillsLearn: [
      { name: "Cooking & Baking", category: "life_skills", subSkill: "Italian Cuisine", level: "Beginner" },
      { name: "Digital Marketing & SEO", category: "business", subSkill: "Growth Hacking", level: "Intermediate" },
    ],
    credits: 21,
    linkedinUrl: "https://linkedin.com/in/elenarodriguez",
    githubUrl: undefined,
    isLinkedInVerified: true,
    isGitHubVerified: false,
    rating: 4.92,
    totalReviews: 39,
    totalSessionsTaught: 48,
    totalSessionsLearned: 19,
    completedExchanges: 8,
    streakDays: 14,
    badges: ["Helpful Teacher", "Skill Explorer"],
    role: "user",
    createdAt: "2024-03-01",
  },
  {
    id: "u5",
    name: "Alex Kim",
    email: "alex@synapselearn.io",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    bio: "AI Research Engineer & FIDE 2100 Chess Master. I teach machine learning fundamentals, deep learning, and chess strategy in exchange for UI design & public speaking.",
    location: "Seattle, WA",
    preferredLanguages: ["English", "Korean"],
    weeklyHours: 7,
    availableDays: [0, 1, 3, 5],
    availableTimes: ["evening", "night"],
    preferredMethods: ["video", "screen_share", "project_based"],
    learningGoals: ["Improve stage presence and presentation skills", "Learn Figma design"],
    interests: ["Neural Networks", "Blitz Chess", "Acoustic Guitar", "Hiking"],
    skillsTeach: [
      { name: "Machine Learning & AI", category: "technology", subSkill: "LLMs & Neural Nets", level: "Expert", yearsOfExp: 6 },
      { name: "Python", category: "technology", subSkill: "PyTorch & NumPy", level: "Expert", yearsOfExp: 8 },
      { name: "Chess", category: "sports", subSkill: "Opening Repertoire & Tactics", level: "Expert", yearsOfExp: 14 },
    ],
    skillsLearn: [
      { name: "UI/UX Design with Figma", category: "creative", subSkill: "Prototyping", level: "Beginner" },
      { name: "Public Speaking & Pitching", category: "business", subSkill: "Stage Presence", level: "Intermediate" },
    ],
    credits: 44,
    linkedinUrl: "https://linkedin.com/in/alexkim",
    githubUrl: "https://github.com/alexkim",
    isLinkedInVerified: true,
    isGitHubVerified: true,
    rating: 4.98,
    totalReviews: 92,
    totalSessionsTaught: 110,
    totalSessionsLearned: 14,
    completedExchanges: 22,
    streakDays: 31,
    badges: ["Helpful Teacher", "Top Mentor", "Consistent Learner", "Skill Explorer"],
    role: "user",
    createdAt: "2023-08-15",
  },
  {
    id: "u6",
    name: "Priya Patel",
    email: "priya@synapselearn.io",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    bio: "Pastry chef and culinary creator. Teaching artisan sourdough baking, handmade pasta, and Indian cuisine. Excited to learn video editing and fitness.",
    location: "Chicago, IL",
    preferredLanguages: ["English", "Hindi", "Gujarati"],
    weeklyHours: 6,
    availableDays: [2, 3, 5, 6],
    availableTimes: ["morning", "afternoon"],
    preferredMethods: ["video", "in_person", "chat"],
    learningGoals: ["Create high-quality recipe videos", "Improve core fitness & stamina"],
    interests: ["Artisan Baking", "Food Photography", "Badminton", "Gardening"],
    skillsTeach: [
      { name: "Cooking & Baking", category: "life_skills", subSkill: "Italian Cuisine & Sourdough", level: "Expert", yearsOfExp: 9 },
      { name: "Content Creation", category: "creative", subSkill: "Food Styling", level: "Intermediate", yearsOfExp: 3 },
    ],
    skillsLearn: [
      { name: "Video Editing", category: "creative", subSkill: "Short-Form Video", level: "Beginner" },
      { name: "Gym & Calisthenics", category: "sports", subSkill: "Mobility & Core", level: "Beginner" },
    ],
    credits: 14,
    linkedinUrl: undefined,
    githubUrl: undefined,
    isLinkedInVerified: false,
    isGitHubVerified: false,
    rating: 4.87,
    totalReviews: 28,
    totalSessionsTaught: 34,
    totalSessionsLearned: 16,
    completedExchanges: 7,
    streakDays: 9,
    badges: ["Helpful Teacher", "Community Builder"],
    role: "user",
    createdAt: "2024-04-10",
  },
  {
    id: "u7",
    name: "David Okafor",
    email: "david@synapselearn.io",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80",
    bio: "Filmmaker & Motion Designer. Specializing in commercial video editing, visual storytelling, and After Effects. Wanting to learn Next.js and SEO.",
    location: "Lagos, Nigeria",
    preferredLanguages: ["English"],
    weeklyHours: 9,
    availableDays: [1, 2, 4, 5, 6],
    availableTimes: ["afternoon", "evening"],
    preferredMethods: ["video", "screen_share", "project_based"],
    learningGoals: ["Build my own interactive portfolio in Next.js", "Master SEO to rank client websites"],
    interests: ["Documentary Filmmaking", "Afrobeats Production", "Web Dev", "Street Photography"],
    skillsTeach: [
      { name: "Video Editing", category: "creative", subSkill: "Color Grading & Sound Design", level: "Expert", yearsOfExp: 7 },
      { name: "Motion Graphics & 3D", category: "creative", subSkill: "After Effects & Keyframing", level: "Advanced", yearsOfExp: 5 },
      { name: "Photography", category: "creative", subSkill: "Lighting & Composition", level: "Advanced", yearsOfExp: 6 },
    ],
    skillsLearn: [
      { name: "Next.js", category: "technology", subSkill: "App Router", level: "Beginner" },
      { name: "Digital Marketing & SEO", category: "business", subSkill: "SEO & Growth", level: "Intermediate" },
    ],
    credits: 26,
    linkedinUrl: "https://linkedin.com/in/davidokafor",
    githubUrl: "https://github.com/davidokafor",
    isLinkedInVerified: true,
    isGitHubVerified: true,
    rating: 4.91,
    totalReviews: 44,
    totalSessionsTaught: 58,
    totalSessionsLearned: 18,
    completedExchanges: 11,
    streakDays: 16,
    badges: ["Helpful Teacher", "Top Mentor", "Fast Learner"],
    role: "user",
    createdAt: "2024-01-20",
  },
  {
    id: "u8",
    name: "Vikram Reddy",
    email: "vikram@synapselearn.io",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    bio: "Badminton athlete & certified Calisthenics trainer. Former university champion. Can coach smash power, court footwork, and bodyweight strength. Want to learn Flutter & Piano.",
    location: "Hyderabad, India",
    preferredLanguages: ["English", "Telugu", "Hindi"],
    weeklyHours: 8,
    availableDays: [0, 2, 4, 6],
    availableTimes: ["morning", "evening"],
    preferredMethods: ["video", "in_person", "project_based"],
    learningGoals: ["Build a workout tracking app using Flutter", "Learn basic piano chords"],
    interests: ["Badminton Tactics", "Calisthenics", "Mobile App Development", "Rock Climbing"],
    skillsTeach: [
      { name: "Badminton", category: "sports", subSkill: "Footwork & Smash Technique", level: "Expert", yearsOfExp: 10 },
      { name: "Gym & Calisthenics", category: "sports", subSkill: "Bodyweight Training", level: "Advanced", yearsOfExp: 6 },
    ],
    skillsLearn: [
      { name: "Flutter", category: "technology", subSkill: "State Management & UI", level: "Beginner" },
      { name: "Piano & Keys", category: "creative", subSkill: "Chords & Ear Training", level: "Beginner" },
    ],
    credits: 22,
    linkedinUrl: "https://linkedin.com/in/vikramreddy",
    githubUrl: undefined,
    isLinkedInVerified: true,
    isGitHubVerified: false,
    rating: 4.94,
    totalReviews: 32,
    totalSessionsTaught: 41,
    totalSessionsLearned: 15,
    completedExchanges: 8,
    streakDays: 20,
    badges: ["Helpful Teacher", "Community Builder"],
    role: "user",
    createdAt: "2023-12-10",
  },
  {
    id: "u9",
    name: "Amina Al-Sayed",
    email: "amina@synapselearn.io",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80",
    bio: "Fintech Product Manager and startup consultant. Native Arabic speaker. Teaching financial modeling, pitch deck creation, and Arabic in exchange for Machine Learning & Python.",
    location: "Dubai, UAE",
    preferredLanguages: ["Arabic", "English"],
    weeklyHours: 6,
    availableDays: [1, 3, 5],
    availableTimes: ["afternoon", "evening"],
    preferredMethods: ["video", "screen_share", "chat"],
    learningGoals: ["Apply ML models to quantitative trading & risk management"],
    interests: ["Fintech", "Venture Capital", "Arabic Calligraphy", "Tennis"],
    skillsTeach: [
      { name: "Personal Finance & Investing", category: "business", subSkill: "Financial Modeling", level: "Expert", yearsOfExp: 7 },
      { name: "Entrepreneurship & Startups", category: "business", subSkill: "Pitching & GTM", level: "Advanced", yearsOfExp: 5 },
      { name: "Arabic", category: "languages", subSkill: "Modern Standard Arabic", level: "Expert", yearsOfExp: 15 },
    ],
    skillsLearn: [
      { name: "Machine Learning & AI", category: "technology", subSkill: "Neural Networks", level: "Beginner" },
      { name: "Python", category: "technology", subSkill: "Pandas & NumPy", level: "Intermediate" },
    ],
    credits: 30,
    linkedinUrl: "https://linkedin.com/in/amina-alsayed",
    githubUrl: "https://github.com/amina-fintech",
    isLinkedInVerified: true,
    isGitHubVerified: true,
    rating: 4.97,
    totalReviews: 46,
    totalSessionsTaught: 58,
    totalSessionsLearned: 12,
    completedExchanges: 10,
    streakDays: 19,
    badges: ["Helpful Teacher", "Top Mentor", "Fast Learner"],
    role: "user",
    createdAt: "2023-10-01",
  },
];

export const DEMO_ROOMS: LearningRoom[] = [
  {
    id: "room-1",
    title: "Python & Machine Learning Study Circle",
    description: "Weekly collaborative study session breaking down PyTorch, deep learning papers, and building hands-on AI projects.",
    category: "technology",
    skill: "Machine Learning & AI",
    subSkill: "Neural Networks & LLMs",
    level: "Intermediate",
    hostId: "u5",
    participants: ["u1", "u2", "u3", "u9"],
    maxParticipants: 8,
    scheduledAt: new Date(Date.now() + 86400000 * 2).toISOString(),
    duration: 90,
    status: "open",
    credits: 1,
    goals: [
      "Understand Attention Mechanism & Transformers",
      "Implement a mini GPT from scratch in Python",
      "Live code review of member projects",
    ],
    chatMessages: [
      { id: "m1", senderId: "u5", senderName: "Alex Kim", text: "Welcome everyone! Please review chapter 4 on attention before Tuesday.", timestamp: new Date(Date.now() - 3600000 * 5).toISOString() },
      { id: "m2", senderId: "u1", senderName: "Sarah Chen", text: "Excited! I have the PyTorch notebook ready to share.", timestamp: new Date(Date.now() - 3600000 * 2).toISOString() },
    ],
  },
  {
    id: "room-2",
    title: "Cricket Batting Mastery & Tactical Strategy",
    description: "Deep dive into batting footwork against pace & spin, match situations, and fitness drills for serious cricketers.",
    category: "sports",
    skill: "Cricket",
    subSkill: "Batting Technique",
    level: "Intermediate",
    hostId: "u3",
    participants: ["u6", "u8"],
    maxParticipants: 6,
    scheduledAt: new Date(Date.now() + 86400000 * 3).toISOString(),
    duration: 60,
    status: "open",
    credits: 1,
    goals: [
      "Fixing backlift and head alignment",
      "Reading spin variations out of the hand",
      "Match day mental prep & power hitting routines",
    ],
    chatMessages: [
      { id: "cm1", senderId: "u3", senderName: "Arjun Sharma", text: "We will be analyzing video clips of forward defensive & pull shots this week.", timestamp: new Date(Date.now() - 3600000 * 8).toISOString() },
    ],
  },
  {
    id: "room-3",
    title: "Creative Video Editing & YouTube Storytelling",
    description: "Master pacing, sound design, and color grading in Premiere & DaVinci Resolve. Perfect for creators looking to elevate their visuals.",
    category: "creative",
    skill: "Video Editing",
    subSkill: "Premiere Pro & DaVinci",
    level: "All Levels" as unknown as import("@/types").SkillLevel,
    hostId: "u2",
    participants: ["u1", "u6", "u7"],
    maxParticipants: 6,
    scheduledAt: new Date(Date.now() + 86400000 * 4).toISOString(),
    duration: 75,
    status: "open",
    credits: 1,
    goals: [
      "Creating dynamic B-roll transitions",
      "Auditory mixing & choosing the right background music",
      "Export settings for crisp 4K uploads",
    ],
    chatMessages: [
      { id: "vm1", senderId: "u2", senderName: "Marcus Johnson", text: "Drop your raw footage clips in the shared folder before class!", timestamp: new Date(Date.now() - 3600000 * 12).toISOString() },
    ],
  },
  {
    id: "room-4",
    title: "Conversational Spanish Coffee Chat",
    description: "Casual 100% Spanish conversation practice discussing travel, food, and daily life. Friendly and encouraging atmosphere.",
    category: "languages",
    skill: "Spanish",
    subSkill: "Conversational & Grammar",
    level: "Beginner",
    hostId: "u4",
    participants: ["u1", "u5", "u9"],
    maxParticipants: 5,
    scheduledAt: new Date(Date.now() + 86400000 * 5).toISOString(),
    duration: 60,
    status: "open",
    credits: 1,
    goals: [
      "Ordering in restaurants and asking directions",
      "Past tense vs imperfect practice",
      "Idiomatic expressions used in Spain & Latin America",
    ],
    chatMessages: [
      { id: "sm1", senderId: "u4", senderName: "Elena Rodriguez", text: "¡Hola a todos! Prepárense para hablar de sus viajes favoritos.", timestamp: new Date(Date.now() - 3600000 * 15).toISOString() },
    ],
  },
];

export const DEMO_EXCHANGES: SkillExchangeOffer[] = [
  {
    id: "ex-1",
    userId: "u1",
    teachSkill: "React & Next.js",
    teachLevel: "Expert",
    learnSkill: "Video Editing (Premiere / DaVinci)",
    learnLevel: "Intermediate",
    description: "I will mentor you in React, modern hooks, Next.js App Router, and clean state architecture in exchange for coaching on YouTube video editing and color grading.",
    status: "active",
    createdAt: "2024-04-01",
  },
  {
    id: "ex-2",
    userId: "u2",
    teachSkill: "Video Editing & Figma UI/UX",
    teachLevel: "Expert",
    learnSkill: "Python & Backend APIs",
    learnLevel: "Beginner",
    description: "Can teach you how to build stunning Figma design systems and edit cinematic videos if you can teach me Python and connecting backend databases.",
    status: "active",
    createdAt: "2024-04-02",
  },
  {
    id: "ex-3",
    userId: "u3",
    teachSkill: "Cricket Batting & Sports Fitness",
    teachLevel: "Expert",
    learnSkill: "Python Data Science",
    learnLevel: "Beginner",
    description: "Former state level cricketer offering personal batting mechanics and calisthenics coaching in exchange for Python data analysis lessons.",
    status: "active",
    createdAt: "2024-04-03",
  },
  {
    id: "ex-4",
    userId: "u4",
    teachSkill: "Spanish Fluency & Yoga",
    teachLevel: "Expert",
    learnSkill: "Italian Cooking & Pasta Making",
    learnLevel: "Beginner",
    description: "Native Spanish speaker & certified yoga teacher seeking an authentic Italian cooking coach to master pasta and sauces.",
    status: "active",
    createdAt: "2024-04-04",
  },
  {
    id: "ex-5",
    userId: "u5",
    teachSkill: "Machine Learning & Chess Strategy",
    teachLevel: "Expert",
    learnSkill: "Public Speaking & Pitching",
    learnLevel: "Intermediate",
    description: "Offering deep dive sessions on AI neural networks or FIDE-level chess strategy in return for public speaking and presentation coaching.",
    status: "active",
    createdAt: "2024-04-05",
  },
];

export const DEMO_LEARNING_PATHS: LearningPath[] = [
  {
    id: "path-web-dev",
    title: "Become a Modern Full-Stack Web Developer",
    description: "From basic HTML/CSS to React, Next.js, backend architecture, and deploying high-scale web apps.",
    category: "technology",
    targetRole: "Full-Stack Engineer",
    estimatedWeeks: 12,
    stages: [
      {
        stage: 1,
        title: "HTML5 & Semantic Web Foundations",
        description: "Accessible markup, semantic layout elements, and SEO fundamentals.",
        skillsRequired: ["HTML", "Web Accessibility"],
        recommendedMentorIds: ["u1", "u2"],
        projects: ["Build a semantic personal portfolio page"],
        practiceTasks: ["Audit a site with Lighthouse", "Create accessible form elements"],
        completed: true,
      },
      {
        stage: 2,
        title: "Modern CSS & Tailwind Architecture",
        description: "Flexbox, Grid, container queries, and component styling.",
        skillsRequired: ["CSS", "Tailwind CSS"],
        recommendedMentorIds: ["u1", "u2"],
        projects: ["Responsive multi-page SaaS marketing template"],
        practiceTasks: ["Build an animated mobile navbar", "Implement light/dark mode switch"],
        completed: true,
      },
      {
        stage: 3,
        title: "JavaScript ES6+ & TypeScript",
        description: "Async/await, closures, prototypes, TypeScript interfaces and generics.",
        skillsRequired: ["JavaScript", "TypeScript"],
        recommendedMentorIds: ["u1", "u7"],
        projects: ["Interactive state-driven dashboard widget"],
        practiceTasks: ["Convert a JS project to strict TS", "Implement an event emitter"],
        completed: false,
      },
      {
        stage: 4,
        title: "React & Component Design Patterns",
        description: "Hooks, compound components, state management, and performance tuning.",
        skillsRequired: ["React", "State Management"],
        recommendedMentorIds: ["u1", "u5"],
        projects: ["Real-time collaborative task board"],
        practiceTasks: ["Build custom useDebounce & useLocalStorage hooks", "Optimize re-renders with memo/useMemo"],
        completed: false,
      },
      {
        stage: 5,
        title: "Next.js App Router & Server Components",
        description: "Server Actions, streaming with Suspense, routing and caching strategies.",
        skillsRequired: ["Next.js", "Server Components"],
        recommendedMentorIds: ["u1", "u7"],
        projects: ["Full-stack e-commerce marketplace"],
        practiceTasks: ["Implement dynamic metadata and OG images", "Set up API route handlers"],
        completed: false,
      },
      {
        stage: 6,
        title: "Backend APIs & Database Integration",
        description: "RESTful architecture, Prisma/PostgreSQL, authentication and security.",
        skillsRequired: ["Node.js", "SQL & Databases"],
        recommendedMentorIds: ["u1", "u5"],
        projects: ["Secure user authentication system with session management"],
        practiceTasks: ["Write complex SQL join queries", "Implement JWT & OAuth flows"],
        completed: false,
      },
    ],
  },
  {
    id: "path-cricket-mastery",
    title: "Cricket All-Rounder Masterclass",
    description: "Step-by-step development of batting technique, bowling variations, athletic fielding, and strategic match temperament.",
    category: "sports",
    targetRole: "Club / Competitive Cricketer",
    estimatedWeeks: 10,
    stages: [
      {
        stage: 1,
        title: "Batting Stance, Grip & Backlift Fundamentals",
        description: "Eliminate technical flaws in your initial trigger movement and balance.",
        skillsRequired: ["Cricket", "Batting Technique"],
        recommendedMentorIds: ["u3"],
        projects: ["Video self-analysis of 50 front-foot drives"],
        practiceTasks: ["Drop-ball drill against the wall", "Balance holds in batting stance"],
        completed: true,
      },
      {
        stage: 2,
        title: "Front Foot & Back Foot Strokeplay",
        description: "Mastering the cover drive, straight drive, pull shot, and back-foot punch.",
        skillsRequired: ["Cricket", "Batting Technique"],
        recommendedMentorIds: ["u3"],
        projects: ["Target zone batting challenge: hitting gaps consistently"],
        practiceTasks: ["Net session against throwdowns at 120km/h", "Footwork ladder drills"],
        completed: false,
      },
      {
        stage: 3,
        title: "Tackling Spin & Sweep Variations",
        description: "Using feet to reach the pitch of the ball, reading arm ball and googlies.",
        skillsRequired: ["Cricket", "Spin Bowling"],
        recommendedMentorIds: ["u3"],
        projects: ["Spin simulation drill in the nets"],
        practiceTasks: ["Traditional sweep & paddle sweep practice", "Stepping out drills"],
        completed: false,
      },
      {
        stage: 4,
        title: "Match Tactics & Pressure Situations",
        description: "Pacing an innings, running between wickets, death overs power hitting.",
        skillsRequired: ["Cricket", "Cricket Strategy"],
        recommendedMentorIds: ["u3"],
        projects: ["Scenario simulation: Chasing 40 off 24 balls"],
        practiceTasks: ["Target yorker defense", "High-intensity fitness intervals"],
        completed: false,
      },
    ],
  },
  {
    id: "path-ai-engineer",
    title: "AI & Machine Learning Engineering",
    description: "From Python fundamentals and calculus to transformer models, prompt engineering, and deploying AI systems.",
    category: "technology",
    targetRole: "AI/ML Engineer",
    estimatedWeeks: 14,
    stages: [
      {
        stage: 1,
        title: "Python for Data Science & Math Foundations",
        description: "NumPy vectorization, Pandas dataframes, Linear Algebra, and Calculus.",
        skillsRequired: ["Python", "Mathematics & Statistics"],
        recommendedMentorIds: ["u5", "u1"],
        projects: ["Exploratory Data Analysis on a Kaggle dataset"],
        practiceTasks: ["Vectorized matrix multiplication in NumPy", "Gradient descent visualization"],
        completed: true,
      },
      {
        stage: 2,
        title: "Supervised & Unsupervised Machine Learning",
        description: "Regression, Decision Trees, Random Forests, XGBoost, and Clustering.",
        skillsRequired: ["Machine Learning & AI"],
        recommendedMentorIds: ["u5"],
        projects: ["Predictive pricing model with hyperparameter tuning"],
        practiceTasks: ["Feature engineering pipeline", "Cross-validation assessment"],
        completed: false,
      },
      {
        stage: 3,
        title: "Deep Learning & Neural Networks",
        description: "PyTorch, backpropagation, CNNs for vision, RNNs/Transformers for sequences.",
        skillsRequired: ["Python", "Machine Learning & AI"],
        recommendedMentorIds: ["u5"],
        projects: ["Image classifier and sentiment analysis pipeline"],
        practiceTasks: ["Write a multi-layer perceptron from scratch", "PyTorch training loop with TensorBoard"],
        completed: false,
      },
      {
        stage: 4,
        title: "Large Language Models & Agentic Systems",
        description: "Embeddings, vector databases, RAG architecture, function calling, and LLM fine-tuning.",
        skillsRequired: ["Machine Learning & AI"],
        recommendedMentorIds: ["u5", "u1"],
        projects: ["Full autonomous RAG assistant with external tools"],
        practiceTasks: ["Vector search ranking", "Prompt optimization benchmarking"],
        completed: false,
      },
    ],
  },
];

export const DEMO_SESSIONS: Session[] = [
  {
    id: "s1",
    teacherId: "u1",
    learnerId: "u2",
    skill: "React",
    subSkill: "Next.js App Router",
    scheduledAt: new Date(Date.now() + 86400000).toISOString(),
    duration: 60,
    status: "pending",
    type: "1on1",
    credits: 1,
    meetingLink: "https://meet.synapselearn.io/s1",
    notes: "Review Marcus's portfolio code and transition to Next.js",
  },
  {
    id: "s2",
    teacherId: "u2",
    learnerId: "u1",
    skill: "Video Editing",
    subSkill: "Color Grading in DaVinci",
    scheduledAt: new Date(Date.now() + 172800000).toISOString(),
    duration: 60,
    status: "pending",
    type: "1on1",
    credits: 1,
    meetingLink: "https://meet.synapselearn.io/s2",
    notes: "Teaching Sarah node-based color correction and LUT application",
  },
  {
    id: "s3",
    teacherId: "u3",
    learnerId: "u8",
    skill: "Cricket",
    subSkill: "Batting Technique",
    scheduledAt: new Date(Date.now() - 86400000).toISOString(),
    duration: 60,
    status: "completed",
    type: "1on1",
    credits: 1,
    notes: "Analyzed batting stance and bat speed drills",
  },
  {
    id: "s4",
    teacherId: "u5",
    learnerId: "u4",
    skill: "Machine Learning & AI",
    subSkill: "Neural Networks Intro",
    scheduledAt: new Date(Date.now() - 172800000).toISOString(),
    duration: 90,
    status: "completed",
    type: "1on1",
    credits: 2,
    notes: "Elena learned core math behind neural weights and activations",
  },
];

export const DEMO_REVIEWS: Review[] = [
  {
    id: "r1",
    sessionId: "s3",
    reviewerId: "u8",
    revieweeId: "u3",
    rating: 5,
    comment: "Coach Arjun transformed my batting stance in just one session. His breakdown of balance and head position was eye-opening!",
    skillTaught: "Cricket (Batting Technique)",
    sessionQuality: "Excellent",
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "r2",
    sessionId: "s4",
    reviewerId: "u4",
    revieweeId: "u5",
    rating: 5,
    comment: "Alex is an extraordinary AI tutor. He made neural networks intuitive without dumbing down the mathematics. Highly recommend!",
    skillTaught: "Machine Learning & AI",
    sessionQuality: "Excellent",
    createdAt: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    id: "r3",
    sessionId: "s1-old",
    reviewerId: "u2",
    revieweeId: "u1",
    rating: 5,
    comment: "Sarah explained React hooks and state sync so clearly. We refactored my app in real time. Can't wait for our next session.",
    skillTaught: "React",
    sessionQuality: "Excellent",
    createdAt: new Date(Date.now() - 345600000).toISOString(),
  },
];

export const DEMO_RECORDINGS: Recording[] = [
  {
    id: "rec1",
    teacherId: "u1",
    title: "Mastering React Server Components & Next.js 15",
    description: "Understand the mental model of Server vs Client components with hands-on streaming architecture examples.",
    category: "technology",
    skill: "React",
    level: "Intermediate",
    thumbnailUrl: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    duration: 596, // seconds
    views: 1840,
    likes: 342,
    learningObjectives: [
      "Deconstruct Server vs Client component boundaries in Next.js",
      "Implement Suspense boundaries for zero-waterfall streaming",
      "Optimize data serialization over the wire"
    ],
    relatedSkills: ["Next.js", "TypeScript", "FastAPI"],
    practicePrompt: "Build a server component that streams peer activity with an instant fallback skeleton.",
    published: true,
    createdAt: new Date(Date.now() - 604800000).toISOString(),
    tags: ["React", "Next.js", "Server Components", "Frontend"],
  },
  {
    id: "rec2",
    teacherId: "u3",
    title: "Cricket: Perfecting the Cover Drive & Front Foot Transfer",
    description: "Frame-by-frame biomechanical breakdown of foot movement, high elbow, and crisp stroke execution.",
    category: "sports",
    skill: "Cricket",
    level: "Intermediate",
    thumbnailUrl: "https://images.unsplash.com/photo-1531415074868-036b1c57e359?w=800",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    duration: 653,
    views: 2450,
    likes: 512,
    learningObjectives: [
      "Master the 45-degree front foot stride toward the line of the ball",
      "Lock the top wrist with high elbow alignment through impact",
      "Maintain head stability over the ball to eliminate aerial edges"
    ],
    relatedSkills: ["Batting", "Bowling", "Athletic Conditioning"],
    practicePrompt: "Perform 30 dry front-foot shadow drives in front of a mirror focusing on head alignment over knee.",
    published: true,
    createdAt: new Date(Date.now() - 1209600000).toISOString(),
    tags: ["Cricket", "Batting", "Sports", "Technique"],
  },
  {
    id: "rec3",
    teacherId: "u2",
    title: "Cinematic Color Grading & Film Emulation in DaVinci Resolve",
    description: "Learn log curves, color space transform, node trees, and how to emulate organic 35mm film textures.",
    category: "creative",
    skill: "Video Editing",
    level: "Advanced",
    thumbnailUrl: "https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    duration: 900,
    views: 1270,
    likes: 295,
    learningObjectives: [
      "Setup DaVinci YRGB Color Managed timeline architecture",
      "Build a balanced 6-node serial tree: Exposure, Balance, Contrast, Saturation, Halation, Look",
      "Grade skin tones accurately using vector scopes"
    ],
    relatedSkills: ["DaVinci Resolve", "Premiere Pro", "Motion Graphics"],
    practicePrompt: "Grade a high-contrast RAW daylight clip to match a warm 1970s film palette.",
    published: true,
    createdAt: new Date(Date.now() - 1814400000).toISOString(),
    tags: ["Video Editing", "DaVinci Resolve", "Color Grading", "Film"],
  },
  {
    id: "rec4",
    teacherId: "u4",
    title: "Fast Bowling Biomechanics: Seam Control & Arm Speed",
    description: "Biomechanics of the delivery stride, front-knee brace, wrist snap, and seam positioning.",
    category: "sports",
    skill: "Cricket",
    level: "Advanced",
    thumbnailUrl: "https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=800",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    duration: 720,
    views: 3100,
    likes: 640,
    learningObjectives: [
      "Maximize kinetic chain transfer through a braced front knee",
      "Calibrate wrist cock and release angle for upright seam stability",
      "Optimize run-up rhythm to convert linear momentum into rotational speed"
    ],
    relatedSkills: ["Fast Bowling", "Cricket", "Mobility"],
    practicePrompt: "Record 6 deliveries with slow-motion side-on camera to measure front-knee flex angle at release.",
    published: true,
    createdAt: new Date(Date.now() - 2419200000).toISOString(),
    tags: ["Cricket", "Bowling", "Biomechanics", "Pace"],
  },
  {
    id: "rec5",
    teacherId: "u5",
    title: "Building Production Multi-Agent Systems with LLMs",
    description: "Architect stateful multi-agent workflows, tool execution loops, and robust evaluation benchmarks.",
    category: "technology",
    skill: "Python",
    level: "Expert",
    thumbnailUrl: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
    duration: 840,
    views: 4200,
    likes: 890,
    learningObjectives: [
      "Design supervisor-worker multi-agent message topologies",
      "Implement structured JSON output schema validation",
      "Mitigate hallucinations with grounded retrieval and verified tools"
    ],
    relatedSkills: ["Python", "FastAPI", "Deep Learning"],
    practicePrompt: "Create a pair of cooperating agents: a Code Planner and a Code Auditor with tool feedback loops.",
    published: true,
    createdAt: new Date(Date.now() - 3024000000).toISOString(),
    tags: ["AI", "Python", "LLMs", "Agents"],
  },
  {
    id: "rec6",
    teacherId: "u6",
    title: "Conversational Spanish Fluency: Idioms, Cadence & Everyday Flow",
    description: "Ditch textbook phrases for natural native idioms, listening drills, and conversational cadence.",
    category: "languages",
    skill: "Spanish",
    level: "Beginner",
    thumbnailUrl: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    duration: 610,
    views: 1950,
    likes: 420,
    learningObjectives: [
      "Master high-frequency colloquial connectors (por cierto, o sea, en fin)",
      "Train ear for rapid natural liaisons and dropped syllables",
      "Conduct a 10-minute spontaneous dialogue without English fallback"
    ],
    relatedSkills: ["Spanish", "Pronunciation", "Public Speaking"],
    practicePrompt: "Record a 2-minute voice note describing your daily routine using 5 colloquial connectors.",
    published: true,
    createdAt: new Date(Date.now() - 3628800000).toISOString(),
    tags: ["Languages", "Spanish", "Fluency", "Conversation"],
  }
];

export const DEMO_TIME_SLOTS: TimeSlot[] = [
  { id: "t1", userId: "u1", dayOfWeek: 1, startTime: "17:00", endTime: "18:00", isAvailable: true },
  { id: "t2", userId: "u1", dayOfWeek: 3, startTime: "18:00", endTime: "19:00", isAvailable: true },
  { id: "t3", userId: "u1", dayOfWeek: 5, startTime: "16:00", endTime: "17:00", isAvailable: true },
  { id: "t4", userId: "u2", dayOfWeek: 2, startTime: "14:00", endTime: "15:00", isAvailable: true },
  { id: "t5", userId: "u2", dayOfWeek: 4, startTime: "15:00", endTime: "16:00", isAvailable: true },
  { id: "t6", userId: "u3", dayOfWeek: 0, startTime: "08:00", endTime: "09:00", isAvailable: true },
  { id: "t7", userId: "u3", dayOfWeek: 2, startTime: "17:00", endTime: "18:00", isAvailable: true },
  { id: "t8", userId: "u3", dayOfWeek: 6, startTime: "09:00", endTime: "10:00", isAvailable: true },
  { id: "t9", userId: "u5", dayOfWeek: 1, startTime: "19:00", endTime: "20:30", isAvailable: true },
  { id: "t10", userId: "u5", dayOfWeek: 3, startTime: "19:00", endTime: "20:30", isAvailable: true },
];

export const DEMO_CREDIT_TRANSACTIONS: CreditTransaction[] = [
  { id: "c1", userId: "u1", amount: 1, type: "earned", description: "Taught React 1-on-1 to Marcus", createdAt: new Date(Date.now() - 604800000).toISOString() },
  { id: "c2", userId: "u1", amount: -1, type: "spent", description: "Learned Video Editing from Marcus", createdAt: new Date(Date.now() - 518400000).toISOString() },
  { id: "c3", userId: "u3", amount: 1, type: "earned", description: "Taught Cricket Batting to Vikram", createdAt: new Date(Date.now() - 86400000).toISOString() },
  { id: "c4", userId: "u5", amount: 2, type: "earned", description: "Taught Machine Learning to Elena", createdAt: new Date(Date.now() - 172800000).toISOString() },
];

export const DEMO_CONNECTIONS: Connection[] = [
  { id: "conn-1", requesterId: "u1", receiverId: "u2", status: "accepted", message: "Hi Marcus! Would love to swap React for Video Editing.", createdAt: "2024-03-10" },
  { id: "conn-2", requesterId: "u3", receiverId: "u1", status: "accepted", message: "Hey Sarah, I'm analyzing cricket data and need Python pointers!", createdAt: "2024-03-15" },
  { id: "conn-3", requesterId: "u5", receiverId: "u1", status: "accepted", message: "Hi Sarah, let's collaborate on AI web app prototypes.", createdAt: "2024-03-20" },
  { id: "conn-4", requesterId: "u4", receiverId: "u1", status: "pending", message: "Hi! Would love to practice Spanish and learn tech tips.", createdAt: "2024-04-05" },
];

export const DEMO_CONVERSATIONS: Conversation[] = [
  {
    id: "conv-1",
    participantIds: ["u1", "u2"],
    lastMessage: "Sounds great! Let's connect on Wednesday at 5pm.",
    lastMessageTime: new Date(Date.now() - 3600000).toISOString(),
    unreadCount: 0,
  },
  {
    id: "conv-2",
    participantIds: ["u1", "u3"],
    lastMessage: "Thanks Sarah! The pandas groupby example made total sense.",
    lastMessageTime: new Date(Date.now() - 86400000).toISOString(),
    unreadCount: 1,
  },
];

export const DEMO_MESSAGES: Message[] = [
  { id: "msg-1", conversationId: "conv-1", senderId: "u2", text: "Hey Sarah! Saw your profile on SynapseLearn. I'd love to exchange video editing for React tips.", createdAt: new Date(Date.now() - 86400000 * 2).toISOString(), read: true },
  { id: "msg-2", conversationId: "conv-1", senderId: "u1", text: "Hi Marcus! That's literally the exact skill swap I've been looking for. When are you free?", createdAt: new Date(Date.now() - 86400000).toISOString(), read: true },
  { id: "msg-3", conversationId: "conv-1", senderId: "u2", text: "I have available slots on Wednesday evening!", createdAt: new Date(Date.now() - 7200000).toISOString(), read: true },
  { id: "msg-4", conversationId: "conv-1", senderId: "u1", text: "Sounds great! Let's connect on Wednesday at 5pm.", createdAt: new Date(Date.now() - 3600000).toISOString(), read: true },
  { id: "msg-5", conversationId: "conv-2", senderId: "u3", text: "Hey Sarah, could you check this quick Python snippet when you get a chance?", createdAt: new Date(Date.now() - 86400000).toISOString(), read: false },
];

export const DEMO_NOTIFICATIONS: NotificationItem[] = [
  { id: "n1", userId: "u1", type: "match", title: "New 95% Compatibility Match!", message: "Marcus Johnson wants to learn Python/React and teaches Video Editing.", link: "/matches", read: false, createdAt: new Date(Date.now() - 1800000).toISOString() },
  { id: "n2", userId: "u1", type: "connection_request", title: "Connection Request", message: "Elena Rodriguez sent you a connection request.", link: "/connections", read: false, createdAt: new Date(Date.now() - 7200000).toISOString() },
  { id: "n3", userId: "u1", type: "room_invite", title: "Learning Room Live", message: "Python & Machine Learning Study Circle starts in 2 days.", link: "/groups", read: true, createdAt: new Date(Date.now() - 86400000).toISOString() },
];
